plugin:
  prefix: "<rainbow><bold>ᴄᴇɴᴄʜᴀɴᴛs » </bold></rainbow> <reset>"


# Configuration for enchantments (enchants)
enchants:
  # Heal enchantment
  heal:
    description: "Restore a portion of health to yourself." # Description of the heal enchantment
    max_level: 10  # Maximum level for the heal enchantment
    chance: 200     # Chance (in percentage , 1000% is a guaranteed effect apply) to successfully apply the heal effect

  # Lightning enchantment
  lightning:
    description: "Strike your enemies with a lightning." # Description of the lightning enchantment
    max_level: 10  # Maximum level for the lightning enchantment
    chance: 200     # Chance (in percentage , 1000% is a guaranteed effect apply) to successfully apply the lightning effect

  # Confusion enchantment
  confusion:
    description: "Randomly shuffles the target's hotbar." # Description of the confusion enchantment
    max_level: 10  # Maximum level for the frost enchantment
    chance: 200     # Chance (in percentage , 1000% is a guaranteed effect apply) to successfully apply the frost effect
