name: CustomEnchants
version: '1.0'
main: org.flennn.CustomEnchants
api-version: '1.20'
author: flennn

commands:
  customenchant:
    description: "Custom Enchants commands"
    usage: "/customenchant <subcommand>"
    aliases: [ ce,cenchant,customenchants,cenchants ]
